Minor cleanup.

diff --git a/prusa-cam b/prusa-cam
--- a/prusa-cam
+++ b/prusa-cam
@@ -1,27 +1,50 @@
 #!/bin/bash
 
-# Set default values for environment variables
-: "${HTTP_URL:=https://connect.prusa3d.com/c/snapshot}"
-: "${DELAY_SECONDS:=10}"
-: "${LONG_DELAY_SECONDS:=60}"
+#### Helper functions ####
 
+#
+# log message with date/time
+#
+log() {
+    printf '%s %s\n' "$(date +"%Y-%m-%d %H:%M:%S")" "$*"
+}
+
+# log error with date/time to stderr
+log_err() {
+    printf '%s %s\n' "$(date +"%Y-%m-%d %H:%M:%S")" "$*" >&2
+}
+
+#### Set default values for environment variables ####
+
+# Where to upload the still image.
+HTTP_URL=https://connect.prusa3d.com/c/snapshot
+
+# How often to upload an image.
+DELAY_SECONDS=10
+
+# How long to wait if there is an error.
+LONG_DELAY_SECONDS=60
+
+#
 # Read the secrets file from command line parameter and export variables
 # Expect the secrets file path as the first positional argument.
+#
 SECRETS_FILE="$1"
-
 if [ -z "$SECRETS_FILE" ]; then
     echo "Usage: $0 /path/to/secrets_file"
+    echo 
     echo "Secrets file must exist and contain the following values:"
-    echo "FINGERPRINT=<a UUID unique to this camera instance>"
-    echo "CAMERA_TOKEN=<token assigned by Prusa Connect>"
-    echo "PRINTER_HOSTNAME=<hostname or IP of your printer>"
-    echo "PRINTER_USERNAME=<your PrusaLink user name (NOT your PrusaConnect user e.g. 'maker')"
-    echo "PRINTER_PASSWORD=<your PrusaLink password (again, NOT PrusaConnect)"
+    echo 
+    echo -e "\tFINGERPRINT=<a UUID unique to this camera instance>"
+    echo -e "\tCAMERA_TOKEN=<token assigned by Prusa Connect>"
+    echo -e "\tPRINTER_HOSTNAME=<hostname or IP of your printer>"
+    echo -e "\tPRINTER_USERNAME=<your PrusaLink user name (NOT your PrusaConnect user e.g. 'maker')"
+    echo -e "\tPRINTER_PASSWORD=<your PrusaLink password (again, NOT PrusaConnect)"
     exit 1
 fi
 
 if [ ! -f "$SECRETS_FILE" ]; then
-    echo "Error: Secrets file '$SECRETS_FILE' not found. Provide a valid path as the first argument."
+    log_err "***ERROR: Secrets file '$SECRETS_FILE' not found. Provide a valid path as the first argument."
     exit 1
 fi
 
@@ -29,13 +52,17 @@ set -a
 source "$SECRETS_FILE"
 set +a
 
-echo "Starting Image Capture for Prusa Connect\n"
-echo "HTTP_URL: $HTTP_URL"
-echo "DELAY_SECONDS: $DELAY_SECONDS"
-echo "LONG_DELAY_SECONDS: $LONG_DELAY_SECONDS"
-echo "FINGERPRINT: $FINGERPRINT"
-echo "PRINTER_HOSTNAME: $PRINTER_HOSTNAME"
-echo "PRINTER_USERNAME: $PRINTER_USERNAME"
+#
+# Show the user what we found.
+#
+log "Starting Image Capture for Prusa Connect"
+echo 
+echo -e "\tHTTP_URL: $HTTP_URL"
+echo -e "\tDELAY_SECONDS: $DELAY_SECONDS"
+echo -e "\tLONG_DELAY_SECONDS: $LONG_DELAY_SECONDS"
+echo -e "\tFINGERPRINT: $FINGERPRINT"
+echo -e "\tPRINTER_HOSTNAME: $PRINTER_HOSTNAME"
+echo -e "\tPRINTER_USERNAME: $PRINTER_USERNAME"
 
 while true; do
 
@@ -44,7 +71,7 @@ while true; do
     # Check to see if the printer is printing...
     PRINT_STATUS=$(curl -s --digest -u $PRINTER_USERNAME:$PRINTER_PASSWORD "$PRINTER_HOSTNAME/api/v1/status" | jq -r '.printer.state')
     if [ $? -ne 0 ]; then
-        echo  $(date +"%Y-%m-%d %H:%M:%S") "*** ERROR getting printer status.  Will retry in ${LONG_DELAY_SECONDS}s..." >&2 
+        log_err "*** ERROR getting printer status.  Will retry in ${LONG_DELAY_SECONDS}s..."
         DELAY=$LONG_DELAY_SECONDS
     else 
         # Upload a still image if we're printing.
@@ -54,7 +81,7 @@ while true; do
             rpicam-jpeg -q 50 --width 800 --height 600 -t 1 -o /tmp/3d_still.jpg
             # If no error, upload it.
             if [ $? -eq 0 ]; then
-            
+
                 # Upload the image to the HTTP URL using curl
                 HTTP_STATUS=$(curl -k -X PUT "$HTTP_URL" \
                     -H "accept: */*" \
@@ -68,21 +95,23 @@ while true; do
                     -o /dev/null)
 
                 if [ $? -ne 0 ] || [ $HTTP_STATUS -lt 200 ] || [ $HTTP_STATUS -ge 300 ]; then
-                    echo $(date +"%Y-%m-%d %H:%M:%S") "*** ERROR uploading image to Prusa Connect (HTTP $HTTP_STATUS). Will retry in ${LONG_DELAY_SECONDS}s..." >&2
+                    log_err "*** ERROR uploading image to Prusa Connect (HTTP $HTTP_STATUS). Will retry in ${LONG_DELAY_SECONDS}s..."
                     DELAY=$LONG_DELAY_SECONDS
                 else
                     # Reset delay to the normal value
                     DELAY=$DELAY_SECONDS
                 fi
             else
-                echo  $(date +"%Y-%m-%d %H:%M:%S") "*** ERROR capturing image.  Will retry in ${LONG_DELAY_SECONDS}s..." >&2 
+                log_err "*** ERROR capturing image.  Will retry in ${LONG_DELAY_SECONDS}s..."
                 # Set delay to the longer value
                 DELAY=$LONG_DELAY_SECONDS
             fi
         else 
-            echo $(date +"%Y-%m-%d %H:%M:%S") "Printer is not printing."
+            log "Printer is not printing."
         fi
     fi
     
     sleep "$DELAY"
 done
+
+
